sudo: required
git:
  depth: false

services:
  - docker

language: c

os:
  - linux
  - osx

dist: xenial
osx_image: xcode8.3

before_install:
  - sudo ./dist/before_build.sh
  - "./dist/before_build.sh"

script: "./dist/build.sh"

deploy:
  - provider: releases
    api_key:
      secure: R7Qo1n7SPn0lumai6BssUVXInVoS3ZylraT0OJOeJpN9iLE4iri4p4unrJV7PiVetxsscGYQ0ijnTG2q0DymjiD0eKNBaMmx5os5mvi1x7VBDtAW1Ki53N/S4EQMF0JKEbeKzuW0Jsp21wGEv3ZDpdq2u8Bf+M1+qEpYz0t8FU8gtFLIrpfszUqv9L+wOcnEwepiZUGRD1czfM7lJ39bkOC5gSaskekcydk3qECzdlZdh4e4vnlI9ymNOvDiaPtBiXgDVBhq4QVCuOy696k2NKD9cpeLLblgxSYDTphQAfLZn93CQ0Knx3wr8YImVJA6qtprPuoPLgS3HWZW0uxVdLqKTsqIH6YbSbjK6Awg1xJhiWJMwK2oDC1EU6+RgeaV7x3KbmT7prJiZQGfhp5mWIxoGvXabLrwh17JInWYyq8+CS3xDdTEykQmZYsAEW6CR96Ie4YnrK9YjwE+PVwUiwyiGhKzdato4br9lKs6nrZpXwydYUvWqNfNeaQtFjiHSkb6Gac2Dj7PliWnScm/qq9imaq/Riz9L/X6Gogw9CFSVdf8pM932Jgl65dIf99BMJT4uBCcWddCpEgKa8/RMRDLp38GiJQbw6CSQUVs4zHBtT2PbiurCp5TBmrRvwOYOAfcbPoTJ+lx9nAG4pULHW2HdXBkC0hRSuTUZOFu/G8=
    file: 
      - build/studio-link-standalone-$BUILD_OS.zip
      - build/studio-link-plugin-$BUILD_OS.zip
      - build/studio-link-plugin-onair-$BUILD_OS.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: "AKIAJ3CDJMCPJXIU5TTA"
    secret_access_key:
      secure: AO/SfGSdeyrMT8/djYgR+TIgnBqggXiW9gaoc208NbcWGfbzgfY3hOse/QSAI7K6qw+sL8HW5i7kf5r6YtHM4g3ProXY5UBF7N7BPjcm1UoPI3W4qOBv2Rr7fX73OhJ+pVjx4jTd+7W87KF4vH5+5DzSfEwgjw4oQxPXEjUj4ZCCeTBMoRas9Qx0h0g+76r9ogXAi9Opke4gp9vz4ONRajaTG+/PPhVGcMlSxEIRgS0S7cqrmpaJ5Dfq4vxjl/eMd2D2LEbC1F2wfegxc2+0aMqlvkmqZYk2rRigZx8ayVasWQGQkX3npgOsy4pRLggn/9d9nt7qqLPkRo/Cd2iGsaNGClTZRiyCc1gN+WIByazQ6RHRYldQhTxOU1VWGk2kR0k+ffMSkIgREc+jGBX/1Upywq2qWK3eyvk6p0h2ynSMdTnxi4c4nJj/4Yp7MGqx/vqjhQmsX/0AGNHSQ49emQOWkCl3AjElmWUJga6vOcXjfugTI0lc816GdufEcKtbTXbOywm86VeLDznwrAcPL+zgZ+HGVjnyb0bGFdJ7B+eLG0pQdut9kxuJKnQH1fstthkBzBA3wJNaoBd0zAH1bgA8cSuXdKaLsn12XfQa05OuLNBaP0Clrdvk7CgPEz7sGqyQxj+tg3QPOTIfQe570UCRo3W7WlMqcRn9PKQV++U=

    bucket: "studio-link-artifacts"
    region: eu-central-1
    local_dir: build/s3_upload
    acl: public_read
    skip_cleanup: true
    on:
      all_branches: true
      condition: $BUILD_OS != ccheck

env:
  matrix:
    - BUILD_OS="windows64"
    - BUILD_OS="windows32"
    - BUILD_OS="linux"         
    - BUILD_OS="osx"

matrix:              
        exclude:            
          - os: osx                
            env: BUILD_OS="windows32"
          - os: osx                
            env: BUILD_OS="windows64"
          - os: osx          
            env: BUILD_OS="linux"         
          - os: linux          
            env: BUILD_OS="osx"

arch:
        packages:
            - wget
            - perl
            - zip
            - unzip
            - vim
            - npm
        script:
            - "./dist/build_windows.sh"
