sudo: required
git:
  depth: false
services:
- docker
language: c
os:
- linux
- osx
dist: xenial
osx_image: xcode10.1
before_install:
- sudo ./dist/before_build.sh
- "./dist/before_build.sh"
script: "./dist/build.sh"
deploy:
  provider: releases
  api_key:
    secure: fyBieKSOG6TeCeQUXacsrfWayZ7DyGwm68LyQ3qVVyJDhFrnMRkWT2+iObdT8yww3EW6uWPqv+LQ4AgGa2ntKwZPodWvvIoE6eXmCFrraM3nHObrl/rZMQgp6zwutior3SIxhJzdZ2orRVHIt6X4wHCstc9n38FFJ0GUKWK5JgUgfv1HI7URjzdlCOoN3fi8O1ATn4hilitLn/nEqcGUTgEqDhvSTek730PuY34Po1TeF0SaqhazQBh6DsChSvZPfsy3QnePByXa45VspCgg9TFj4kAM/gL2ek3qwtk8XsBjnmTjSwWGuBH5p1+bMvV/CJHdXF2MT2ovSJyslW9+2ZVPtqYh6TfCl9auAKOc2u2KdOnhSOZ6QSkO2z+1x2Sdg+iAxm0k8GP6J7JVptzklAqclBzUHPwGTrVHQt0pqFGgcSby4ZlO0WAblF1ABfI8XmPYhx1fHEBZ6cAR0+GL/cqUL8C/HPrM7JQowlGDju+CVx7mFUfgcSiVaUE7imWPDV/ODYfPOKjrAgfUhJo6lXqGPeigdoafZvv1UOfdvP//OTrwH6Ch9R/GzZUqW9J5Lz4pU8qgnIxbhYagZdCzLXvi1Gm52fFMx0ismmuYd2WgBhDXHSlANmaHuLNmtyINilHc6yI/bNPe1wzepbc5WpMB5NVTAVeZGi204k4X0Qk=
  file: build/$BUILD_OS.zip
  skip_cleanup: true
  on:
    tags: true
env:
  matrix:
  - BUILD_OS="windows64"
  - BUILD_OS="linux"
  - BUILD_OS="linuxjack"
  - BUILD_OS="osx"
matrix:
  exclude:
  - os: osx
    env: BUILD_OS="windows64"
  - os: osx
    env: BUILD_OS="linux"
  - os: osx
    env: BUILD_OS="linuxjack"
  - os: linux
    env: BUILD_OS="osx"
archlinux:
  packages:
  - wget
  - perl
  - zip
  - unzip
  - vim
  - npm
  script:
  - "./dist/build_windows.sh"
