name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            env:
              BUILD_TARGET: windows64
              BUILD_OS: archlinux
          - os: ubuntu-20.04
            env:
              BUILD_TARGET: windows32
              BUILD_OS: archlinux
          - os: ubuntu-16.04
            env:
              BUILD_TARGET: linux
              BUILD_OS: linux
          - os: ubuntu-16.04
            env:
              BUILD_TARGET: linuxjack
              BUILD_OS: linux
          - os: macos-10.15
            env:
              BUILD_TARGET: macos_x86_64
              BUILD_OS: macos
          - os: macos-10.15
            env:
              BUILD_TARGET: macos_arm64
              BUILD_OS: macos

    steps:
    - uses: actions/checkout@v2
    - name: make ${{ BUILD_TARGET }}
      run: echo $BUILD_OS
